name: ci

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install
        run: pnpm install --frozen-lockfile
      - name: EsLint
        run: pnpm lint
